# UAT environment configuration
jwt:
  secret: "Ym9va2luZy10aWNrZXQ="
  access_token_ttl: "15m"
  refresh_token_ttl: "168h"

database:
  postgres:
    host: "uat-db.example.com"
    port: 5432
    user: "uat_user"
    password: "uat_password"
    dbname: "authdb_uat"
    sslmode: "require"
    max_open_conns: 50
    max_idle_conns: 10
    conn_max_lifetime: "15m"

redis:
  host: "uat-redis.example.com"
  port: 6379
  password: "uat_redis_password"
  db: 0
  pool_size: 20
  min_idle_conns: 10

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

logging:
  level: "info"
  format: "json"
  output: "stdout"

auth:
  bcrypt_cost: 12
  session_timeout: "24h" 