version: '3.7'

services:
  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: StrongPass!123
      MONGO_INITDB_DATABASE: quizdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-net

volumes:
  mongo-data:

networks:
  mongo-net:
    driver: bridge
