version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: booking-postgres
    environment:
      POSTGRES_USER: booking_app
      POSTGRES_PASSWORD: "X4pV7_qM9%tN1wK6@rG8jM2Z"
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: booking-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "StrongPass!123"]
    volumes:
      - redisdata:/data

  nats:
    image: nats:2.9-alpine
    container_name: booking-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]

  nats-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: nats-ui
    depends_on:
      - nats
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: nats
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: nats:4222

volumes:
  pgdata:
  redisdata: