# Base configuration
jwt:
  secret: "your-secret-key-here"
  access_token_ttl: "15m"
  refresh_token_ttl: "168h"  # 7 days

database:
  postgres:
    host: "localhost"
    port: 5432
    user: "root"
    password: "root"
    dbname: "authdb"
    sslmode: "disable"
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: "5m"

redis:
  host: "localhost"
  port: 6379
  password: "StrongPass!123"
  db: 0
  pool_size: 10
  min_idle_conns: 5

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

logging:
  level: "info"
  format: "json"
  output: "stdout"

auth:
  bcrypt_cost: 12
  session_timeout: "24h" 