# Development environment configuration
jwt:
  secret: "dev-secret-key-123"
  access_token_ttl: "30m"
  refresh_token_ttl: "24h"

database:
  postgres:
    host: "localhost"
    port: 5432
    user: "booking_app"
    password: "X4pV7_qM9%tN1wK6@rG8jM2Z"
    dbname: "booking"
    sslmode: "disable"
    max_open_conns: 10
    max_idle_conns: 3
    conn_max_lifetime: "10m"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 1
  pool_size: 5
  min_idle_conns: 2

server:
  port: 8080
  host: "localhost"
  read_timeout: "60s"
  write_timeout: "60s"
  idle_timeout: "120s"

logging:
  level: "debug"
  format: "text"
  output: "stdout"

auth:
  bcrypt_cost: 10
  session_timeout: "12h" 