# Production environment configuration
jwt:
  secret: "prod-secret-key-789"
  access_token_ttl: "10m"
  refresh_token_ttl: "168h"

database:
  postgres:
    host: "prod-db.example.com"
    port: 5432
    user: "prod_user"
    password: "prod_password"
    dbname: "authdb_prod"
    sslmode: "require"
    max_open_conns: 100
    max_idle_conns: 25
    conn_max_lifetime: "30m"

redis:
  host: "prod-redis.example.com"
  port: 6379
  password: "prod_redis_password"
  db: 0
  pool_size: 50
  min_idle_conns: 20

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

logging:
  level: "warn"
  format: "json"
  output: "stdout"

auth:
  bcrypt_cost: 14
  session_timeout: "24h" 